name: generate-coverage
on: [push]
jobs:
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: psf/black@stable
        with:
          options: "--check --verbose"
  test:
    name: Collect test coverage information using pytest and coverage packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install pytest and coverage
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Collect coverage information
        run: coverage run -m pytest
      - name: Upload coverage file
        uses: actions/upload-artifact@v4
        with:
          name: coverage-file
          path: .coverage
          include-hidden-files: true
          retention-days: 1
  coverage_report:
    name: Create coverage report and its corresponding xml
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install only coverage
        run: |
          python -m pip install --upgrade pip
          pip install coverage>=7.6.10
      - name: Download coverage file
        uses: actions/download-artifact@v4
        with:
          name: coverage-file
      - name: Generate report and xml
        run: |
          coverage report
          coverage xml
      - name: Upload coverage xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          retention-days: 14
           